name: Security audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    name: cargo deny check advisories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
      - name: Install cargo-deny
        run: cargo install --locked cargo-deny
      - name: Run advisories check
        run: make advisories
